version: '3'
services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  mongodb-data:
